### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by fennectech** [friedkeenan/GoldtreePy#10]
Connection was established with Goldleaf.
NSP name sent to Goldleaf
Goldleaf is ready for the installation. Preparing everything...
Sending content 'd3ddfa8835aba73010935e2d8066df99.cnmt.nca'... (5 of 7)
Content was sent to Goldleaf.
Sending ticket file...
Traceback (most recent call last):
  File "Goldtree.py", line 141, in <module>
    sys.exit(main())
  File "Goldtree.py", line 103, in main
    c=Command.read()
  File "Goldtree.py", line 54, in read
    return Command(raw=read(4)+read(4))
  File "Goldtree.py", line 61, in read
    return ep[1].read(length,timeout=timeout).tobytes()
  File "/usr/lib/python3.7/site-packages/usb/core.py", line 402, in read
    return self.device.read(self, size_or_buffer, timeout)
  File "/usr/lib/python3.7/site-packages/usb/core.py", line 988, in read
    self.__get_timeout(timeout))
  File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 833, in bulk_read
    timeout)
  File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 936, in __read
    _check(retval)
  File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 110] Operation timed out

Crashes.

**Comment by friedkeenan** [comment]
Try increasing the 3000 in [these lines](https://github.com/friedkeenan/GoldtreePy/blob/master/Goldtree.py#L58-L61) to something higher, like 10000. If that doesn't work, try with the Goldleaf nightly and the nightly branch of GoldtreePy.

**Comment by fennectech** [comment]
this works.
