### ISSUE TITLE
Install stalls every time on the 4th nca, can't install anything with usb install.

### ISSUE THREAD

**Issue by potjesoep** [friedkeenan/GoldtreePy#3]
I tried to install 2 different nsps, neither succesfully installed with usb install.

goldtreepy exits and the install stalls and goes to 0MB/s. 

using the goldtreepy version for 0.3 and goldleaf 0.3 release nsp

```Connection was established with Goldleaf.
NSP name sent to Goldleaf
Goldleaf is ready for the installation. Preparing everything...
Sending content 'f2f2cdf426106a75c0347fc0d26fa4b5.cnmt.nca'... (5 of 7)
Content was sent to Goldleaf.
Sending ticket file...
Sending content 'c382e7094327e6efe8360312a57cbbd3.nca'... (3 of 7)
Content was sent to Goldleaf.
Traceback (most recent call last):
  File "/home/nekonoor/Scripts/data/GoldtreePy/Goldtree.py", line 135, in <module>
    sys.exit(main())
  File "/home/nekonoor/Scripts/data/GoldtreePy/Goldtree.py", line 97, in main
    c=Command(raw=read(8))
  File "/home/nekonoor/Scripts/data/GoldtreePy/Goldtree.py", line 54, in read
    return ep[1].read(length).tobytes()
  File "/usr/lib/python3.7/site-packages/usb/core.py", line 402, in read
    return self.device.read(self, size_or_buffer, timeout)
  File "/usr/lib/python3.7/site-packages/usb/core.py", line 988, in read
    self.__get_timeout(timeout))
  File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 833, in bulk_read
    timeout)
  File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 936, in __read
    _check(retval)
  File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 110] Operation timed out

**Comment by friedkeenan** [comment]
Could you please try the latest commit? If that doesn't work I'll have to investigate [this line](https://github.com/XorTroll/Goldleaf/blob/master/Goldtree/Goldtree/Program.cs#L173) in the original Goldtree, but I don't see what is different between our implementations

**Comment by potjesoep** [comment]
Same problem with latest commit

```Connection was established with Goldleaf.
NSP name sent to Goldleaf
Goldleaf is ready for the installation. Preparing everything...
Sending content '342c76ea44fc7170ff18fa3def161c84.cnmt.nca'... (5 of 7)
Content was sent to Goldleaf.
Sending ticket file...
Sending content '507e6336ddcace1c352eea8855967887.nca'... (3 of 7)
Content was sent to Goldleaf.
Traceback (most recent call last):
  File "/home/nekonoor/Scripts/data/GoldtreePy/Goldtree.py", line 135, in <module>
    sys.exit(main())
  File "/home/nekonoor/Scripts/data/GoldtreePy/Goldtree.py", line 97, in main
    c=Command(raw=read(8))
  File "/home/nekonoor/Scripts/data/GoldtreePy/Goldtree.py", line 54, in read
    return ep[1].read(length,timeout=timeout).tobytes()
  File "/usr/lib/python3.7/site-packages/usb/core.py", line 402, in read
    return self.device.read(self, size_or_buffer, timeout)
  File "/usr/lib/python3.7/site-packages/usb/core.py", line 988, in read
    self.__get_timeout(timeout))
  File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 833, in bulk_read
    timeout)
  File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 936, in __read
    _check(retval)
  File "/usr/lib/python3.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 110] Operation timed out

**Comment by juliopw** [comment]
I'm having the same problem 

```Connection was established with Goldleaf.
NSP name sent to Goldleaf
Goldleaf is ready for the installation. Preparing everything...
Sending content 'e9e023c0888a0786471f26a797c79a25.cnmt.nca'... (5 of 7)
Content was sent to Goldleaf.
Sending ticket file...
Traceback (most recent call last):
  File "./Goldtree.py", line 135, in <module>
    sys.exit(main())
  File "./Goldtree.py", line 97, in main
    c=Command(raw=read(8))
  File "./Goldtree.py", line 54, in read
    return ep[1].read(length,timeout=timeout).tobytes()
  File "/home/julio/.local/lib/python3.6/site-packages/usb/core.py", line 402, in read
    return self.device.read(self, size_or_buffer, timeout)
  File "/home/julio/.local/lib/python3.6/site-packages/usb/core.py", line 988, in read
    self.__get_timeout(timeout))
  File "/home/julio/.local/lib/python3.6/site-packages/usb/backend/libusb1.py", line 833, in bulk_read
    timeout)
  File "/home/julio/.local/lib/python3.6/site-packages/usb/backend/libusb1.py", line 936, in __read
    _check(retval)
  File "/home/julio/.local/lib/python3.6/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 110] Operation timed out
```

And sometimes this one

```Connection was established with Goldleaf.
NSP name sent to Goldleaf
Goldleaf is ready for the installation. Preparing everything...
Traceback (most recent call last):
  File "./Goldtree.py", line 135, in <module>
    sys.exit(main())
  File "./Goldtree.py", line 90, in main
    write(file.name.encode())
  File "./Goldtree.py", line 52, in write
    ep[0].write(buffer,timeout=timeout)
  File "/home/julio/.local/lib/python3.6/site-packages/usb/core.py", line 387, in write
    return self.device.write(self, data, timeout)
  File "/home/julio/.local/lib/python3.6/site-packages/usb/core.py", line 948, in write
    self.__get_timeout(timeout)
  File "/home/julio/.local/lib/python3.6/site-packages/usb/backend/libusb1.py", line 824, in bulk_write
    timeout)
  File "/home/julio/.local/lib/python3.6/site-packages/usb/backend/libusb1.py", line 920, in __write
    _check(retval)
  File "/home/julio/.local/lib/python3.6/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 32] Pipe error
```

**Comment by friedkeenan** [comment]
@juliopw As far as I know, that second error is out of my hands, as it's either pyusb's or libnx's fault (I think pyusb).

As for the for the problem you're both having, I think I might just need to increase the timeout. Let me finish my homework and get back to y'all

**Comment by juliopw** [comment]
@friedkeenan that's fine. Thanks!

**Comment by vin047** [comment]
I've also been experiencing these issues, though my error number for operation timed out is different

```
usb.core.USBError: [Errno 60] Operation timed out
```

FAT32 SD card, Kosmos 11.7.1, Goldleaf 0.3, macOS 10.13.6

**Comment by friedkeenan** [comment]
Could you guys please try with the latest commit?

**Comment by potjesoep** [comment]
Latest commit fixed it for me, although i get `usb.core.USBError: [Errno 32] Pipe error` when installing another nsp after the first one worked.

I rebooted my switch and i still can't install another nsp.

Rebooted my computer and still can't install any nsp with usb

**Comment by friedkeenan** [comment]
Have you tried replugging the USB cable?

As far as I know, that error is out of my hands

**Comment by juliopw** [comment]
@friedkeenan replugging the cable seems to fix the `Pipe error` for me.

As for your latest commit, it seems to fix the `Operation timed out` error, at least for me. Thank you!

**Comment by potjesoep** [comment]
@friedkeenan replugging the cable does not fix it. I tried several times and i have only gotten pipe error after the first nsp installed. tinfoil + the usb install script works now but goldtreepy doesn't work
